@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor Utente
participant "Registrazione" as A
participant "Verifica Studente" as B
participant "Controlla Credenziali" as C
actor DB_Sapienza

Utente -> A: SendCred(id, password)
activate A

A -> B: Report(id, password)
activate B

B -> C: Registration(id, password)
activate C

C --> B: Registration

destroy C

alt successful case

    B -> A: Registration Accepted

else just exists id

    B -> A: Registration Rejected

deactivate B
    
end

A --> Utente: Done
deactivate A

@enduml
