@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor Segreteria
participant "Inserimento" as A
participant "Facoltà" as B

Segreteria -> A: SendRequest(nomeFacoltà)
activate A

A -> B: Search
activate B


alt Facoltà not Found

    B --> A: Search Accepted
    deactivate B
        
    A --> Segreteria: <<message>> Insertion Complete
    deactivate A
        
else any Facoltà exists

    B --> Segreteria: Search Fail
    destroy B
    
end

@enduml
