@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor Segreteria
participant "Inserimento" as A
participant "Dipartimento" as B
participant "Facoltà" as C

Segreteria -> A: SendRequest(nomeFacoltà)
activate A

A -> C: Search
activate C


alt successful case

    C --> A: Search Accepted
    deactivate C
    A --> Segreteria: List_Facoltà(list(nomeFacoltà)
    deactivate A

    Segreteria -> A: send(list(nomeFacoltà[i]), nomeDipartimento)
    activate A

    A -> B: Report(nomeFacoltà[i], nomeDipartimento)
    activate B
    
    B -> C: FindDipartimento(nomeDipartimento)
    activate C
    
    alt Dipartimento not Found

        C --> B: Search Accepted
        deactivate C
        
        B --> A: <<message>> Insertion Complete
        deactivate B
        
        A --> Segreteria: print("Insertion OK")
        deactivate A

    else
        
        B --> Segreteria: Failure
        destroy C
    end

else any Edificio exists

    B --> Segreteria: Search Fail
    destroy B
    
end

@enduml
